### ISSUE TITLE
Google Map APIの技術調査

### ISSUE THREAD

**Issue by sh0327akg** [ooooose/MusicMap#2]
API使用方法についてまとめる

**Comment by draobfrus** [comment]
以下に
- 概要
- APIの種類と機能
- 想定される機能ごとの利用イメージ
- 認証・設定方法
- 課金形態

をまとめました。

https://www.notion.so/draobfrus/Google-Map-API-9b1ab6a4e1bd46e4b66ac2c979e88a11

**Comment by sh0327akg** [comment]
記載内容が充実しすぎてて流石です！
LGTM 👍 
完了にしちゃってください！
